# apiVersion: v1
# kind: Secret
# metadata:
#   name: django-secrets
# type: Opaque
# stringData:
#   database_url: "postgres://user:pass@postgres.default.svc.cluster.local:5432/dbname"
#   secret_key: "production-secret-key"
